# Generated by Django 3.2.25 on 2026-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text="Sert d'identifiant de connexion.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(help_text='Prénom.', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Compte activé (passe à true après vérification de l'email)."),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Email vérifié via le lien envoyé à l'inscription."),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(help_text='Nom de famille.', max_length=100),
        ),
    ]
