# Generated by Django 3.2.25 on 2026-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Contenu chiffré (Fernet) stocké sur le serveur.', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Piloté via les endpoints activate/deactivate, pas modifiable à l'upload."),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Toujours true pour les documents créés depuis la Phase 1.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Nom affiché du document.', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Taille en bytes du fichier original (avant chiffrement).'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sha256',
            field=models.CharField(blank=True, help_text='SHA-256 du contenu original (avant chiffrement), revérifié à chaque download.', max_length=64),
        ),
    ]
